[package]
name = "tmp_emit2"
version = "0.1.0"
edition = "2021"

[dependencies]
canon-meta = { path = "../canon-utils/canon-meta" }
canon-prompt-events = { path = "../canon-utils/canon-prompt-events" }
canon_event = { package = "canon-runtime-events", path = "../canon-utils/canon-runtime-events" }
serde_json = "1"
