#!/usr/bin/env python3
"""Generate ir.json from repomap output for canon-agent src/."""
import json, re, subprocess, sys

VISIBILITY = "public"

# Module id → source file stem
MODULES = [
    ("sse",               "src/sse.rs"),
    ("reward",            "src/reward.rs"),
    ("agent_commands",    "src/agent_commands.rs"),
    ("main_entry",        "src/main.rs"),
    ("executor",          "src/executor.rs"),
    ("capability",        "src/capability.rs"),
    ("io",                "src/io.rs"),
    ("emit_shell",        "src/emit_shell.rs"),
    ("dispatcher",        "src/dispatcher.rs"),
    ("pipeline",          "src/pipeline.rs"),
    ("runner",            "src/runner.rs"),
    ("slice",             "src/slice.rs"),
    ("evolution",         "src/evolution/mod.rs"),
    ("evolution_lyapunov","src/evolution/lyapunov.rs"),
    ("evolution_rename",  "src/evolution/structural/rename.rs"),
    ("evolution_apply",   "src/evolution/structural/apply.rs"),
    ("evolution_guard",   "src/evolution/structural/guard.rs"),
    ("llm_provider",      "src/llm_provider.rs"),
    ("ir_core",           "src/ir/core.rs"),
    ("ir_artifacts",      "src/ir/artifacts.rs"),
    ("ir_functions",      "src/ir/functions.rs"),
    ("ir_delta",          "src/ir/delta.rs"),
    ("ir_types",          "src/ir/types.rs"),
    ("ir_policy",         "src/ir/policy.rs"),
    ("ir_timeline",       "src/ir/timeline.rs"),
    ("ir_graphs",         "src/ir/graphs.rs"),
    ("ir_proofs",         "src/ir/proofs.rs"),
    ("ir_goals",          "src/ir/goals.rs"),
    ("ir_world_model",    "src/ir/world_model.rs"),
    ("ir_admission",      "src/ir/admission.rs"),
    ("ir_judgment",       "src/ir/judgment.rs"),
    ("ir_learning",       "src/ir/learning.rs"),
    ("ir_errors",         "src/ir/errors.rs"),
    ("ir_gpu",            "src/ir/gpu.rs"),
    ("ir_proposal",       "src/ir/proposal.rs"),
    ("ir_reward",         "src/ir/reward.rs"),
    ("ir_project",        "src/ir/project.rs"),
    ("ir_word",           "src/ir/word.rs"),
    ("ir_ids",            "src/ir/ids.rs"),
    ("bootstrap",         "src/bootstrap.rs"),
    ("meta",              "src/meta.rs"),
    ("observe",           "src/observe.rs"),
    ("ws_server",         "src/ws_server.rs"),
    ("refactor",          "src/refactor.rs"),
    ("call",              "src/call.rs"),
]

# Functions extracted from repomap — (module_id, fn_id, fn_name)
FUNCTIONS = [
    ("sse",                "sse::extract_sse_delta",          "extract_sse_delta"),
    ("sse",                "sse::is_done",                    "is_done"),
    ("reward",             "reward::new",                     "new"),
    ("reward",             "reward::record",                  "record"),
    ("reward",             "reward::trust_threshold_for",     "trust_threshold_for"),
    ("reward",             "reward::update_policy",           "update_policy"),
    ("reward",             "reward::aggregate_reward",        "aggregate_reward"),
    ("reward",             "reward::ranked_nodes",            "ranked_nodes"),
    ("reward",             "reward::entry_for",               "entry_for"),
    ("agent_commands",     "agent_commands::execute_agent_command", "execute_agent_command"),
    ("main_entry",         "main_entry::main",                "main"),
    ("executor",           "executor::execute_deltas",        "execute_deltas"),
    ("executor",           "executor::git_stash",             "git_stash"),
    ("executor",           "executor::rollback",              "rollback"),
    ("executor",           "executor::run_apply_patch",       "run_apply_patch"),
    ("executor",           "executor::run_bash",              "run_bash"),
    ("capability",         "capability::new",                 "new"),
    ("capability",         "capability::add_node",            "add_node"),
    ("capability",         "capability::add_edge",            "add_edge"),
    ("capability",         "capability::node",                "node"),
    ("capability",         "capability::predecessors",        "predecessors"),
    ("capability",         "capability::successors",          "successors"),
    ("capability",         "capability::validate_edges",      "validate_edges"),
    ("capability",         "capability::entropy",             "entropy"),
    ("capability",         "capability::trust_scores",        "trust_scores"),
    ("io",                 "io::load_capability_graph",       "load_capability_graph"),
    ("io",                 "io::save_capability_graph",       "save_capability_graph"),
    ("emit_shell",         "emit_shell::emit_shell",          "emit_shell"),
    ("dispatcher",         "dispatcher::new",                 "new"),
    ("dispatcher",         "dispatcher::with_trust_threshold","with_trust_threshold"),
    ("dispatcher",         "dispatcher::record_output",       "record_output"),
    ("dispatcher",         "dispatcher::dispatch",            "dispatch"),
    ("dispatcher",         "dispatcher::topological_call_order","topological_call_order"),
    ("pipeline",           "pipeline::run_refactor_pipeline", "run_refactor_pipeline"),
    ("pipeline",           "pipeline::record_refactor_reward","record_refactor_reward"),
    ("pipeline",           "pipeline::require_stage",         "require_stage"),
    ("pipeline",           "pipeline::extract_str_field",     "extract_str_field"),
    ("runner",             "runner::run_agent",               "run_agent"),
    ("runner",             "runner::write_ir_to_disk",        "write_ir_to_disk"),
    ("runner",             "runner::write_ledger_to_disk",    "write_ledger_to_disk"),
    ("slice",              "slice::truncate_list",            "truncate_list"),
    ("slice",              "slice::slim_function",            "slim_function"),
    ("slice",              "slice::slice_ir_fields",          "slice_ir_fields"),
    ("slice",              "slice::extract_field",            "extract_field"),
    ("evolution",          "evolution::apply_admitted_deltas","apply_admitted_deltas"),
    ("evolution_lyapunov", "lyapunov::enforce_lyapunov_bound","enforce_lyapunov_bound"),
    ("evolution_rename",   "rename::rename_module",           "rename_module"),
    ("evolution_rename",   "rename::rename_struct",           "rename_struct"),
    ("evolution_rename",   "rename::rename_function",         "rename_function"),
    ("evolution_apply",    "apply::apply_delta_payload",      "apply_delta_payload"),
    ("evolution_guard",    "guard::ensure_module_exists",     "ensure_module_exists"),
    ("evolution_guard",    "guard::ensure_struct_exists",     "ensure_struct_exists"),
    ("evolution_guard",    "guard::ensure_field_exists",      "ensure_field_exists"),
    ("evolution_guard",    "guard::ensure_trait_exists",      "ensure_trait_exists"),
    ("evolution_guard",    "guard::ensure_function_exists",   "ensure_function_exists"),
    ("llm_provider",       "llm_provider::call_llm",          "call_llm"),
    ("bootstrap",          "bootstrap::seed_capability_graph","seed_capability_graph"),
    ("bootstrap",          "bootstrap::seed_refactor_proposal","seed_refactor_proposal"),
    ("meta",               "meta::evolve_capability_graph",   "evolve_capability_graph"),
    ("meta",               "meta::propose_mutations",         "propose_mutations"),
    ("meta",               "meta::apply_mutation",            "apply_mutation"),
    ("meta",               "meta::find_disconnected",         "find_disconnected"),
    ("observe",            "observe::analyze_ir",             "analyze_ir"),
    ("observe",            "observe::ir_observation_to_json", "ir_observation_to_json"),
    ("ws_server",          "ws_server::spawn",                "spawn"),
]

def make_word(s):
    # Word must be a single canonical word — underscores ok, no hyphens
    return re.sub(r'[^a-z0-9_]', '_', s.lower())

def build_module(mid, path):
    return {
        "id": mid,
        "name": make_word(mid),
        "visibility": VISIBILITY,
        "description": f"Module from {path}",
    }

def build_function(mid, fid, fname):
    return {
        "id": fid,
        "name": make_word(fname),
        "module": mid,
        "impl_id": "",
        "trait_function": "",
        "visibility": VISIBILITY,
        "inputs": [],
        "outputs": [],
        "deltas": [],
        "contract": {
            "total": False,
            "deterministic": True,
            "explicit_inputs": True,
            "explicit_outputs": True,
            "effects_are_deltas": False,
        },
    }

ir = {
    "meta": {
        "version": "0.1.0",
        "law_revision": "alpha",
        "description": "canon-agent self-model IR — generated from repomap",
    },
    "version_contract": {
        "current": "0.1.0",
        "compatible_with": [],
        "migration_proofs": [],
    },
    "project": {
        "name": "canon",
        "version": "0.1.0",
        "language": "rust",
    },
    "modules":            [build_module(mid, path) for mid, path in MODULES],
    "module_edges":       [],
    "structs":            [],
    "traits":             [],
    "impls":              [],
    "functions":          [build_function(mid, fid, fname) for mid, fid, fname in FUNCTIONS],
    "call_edges":         [],
    "tick_graphs":        [],
    "loop_policies":      [],
    "ticks":              [],
    "tick_epochs":        [],
    "plans":              [],
    "executions":         [],
    "admissions":         [],
    "applied_deltas":     [],
    "gpu_functions":      [],
    "proposals":          [],
    "judgments":          [],
    "judgment_predicates":[],
    "deltas":             [],
    "proofs": [
        {
            "id": "proof-bootstrap-invariant",
            "invariant": "IR topology is structurally stable at genesis",
            "scope": "structure",
            "evidence": {"uri": "bootstrap://genesis", "hash": "0000000000000000"},
            "proof_object_hash": "bootstrap",
        }
    ],
    "learning":           [],
    "errors":             [],
    "dependencies":       [],
}

print(json.dumps(ir, indent=2))
