[workspace]
members = [
  "canon-utils/reports",
  "algorithms",
  # "canon-capture",
  # "canon-mutation",
  # "orchestration",
  # "canon_telemetry",
  "canon",
  # "canon-analyzer", 
  # "canon-projection",
  # "canon-agent",
  "canon-agent-v2",
  "canon-utils/project_editor",
  "canon-utils/smt-analysis-engine",
  "canon-utils/canon-query",
  "canon-utils/canon-types",
  "canon-utils/graph",
]
exclude = [
  "test_projects",
]
resolver = "2"
