[workspace]
members = [
  "algorithms",
  # "canon-capture",
  "canon-mutation",
  # "orchestration",
  "canon_telemetry",
  "canon",
  # "canon-analyzer", 
  "canon-projection",
  "canon-agent",
  "canon-agent-v2",
  "canon-utils/rename",
  # "canon-utils/smt-analysis-engine",
  "canon-utils/gpjson-rs",
]
exclude = [
  "test_projects",
]
resolver = "2"
