[workspace]
members = [
  "algorithms",
  # "canon-capture",
  "canon-mutation",
  # "orchestration",
  "canon_telemetry",
  "rustc_wrapper/rustc_capture",
  "canon",
  # "canon-analyzer", 
  "canon-projection",
  "canon-agent",
  "canon-agent-v2",
  "canon-utils/rename",
  "rustc_wrapper/analysis_capture",
  "canon-utils/upg_analysis",
  "canon-utils/analysis-engine",
  "gpjson-rs",
  "canon-utils/struct_harvester",
]
exclude = [
  "test_projects",
]
resolver = "2"
