#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="/workspace/ai_sandbox/canon/test_projects/test_rust_projects"
LOG_DIR="/workspace/ai_sandbox/canon/.run_script_logs"
REPORT="/workspace/ai_sandbox/canon/STRUCTURAL_INVARIANTS_REPORT.md"
mkdir -p "$LOG_DIR"

cat > "$REPORT" <<'EOF'
# STRUCTURAL_INVARIANTS_REPORT.md

Generated by `run_script.sh` from failing pipeline stages.
Only direct facts from tool output are recorded.

EOF

run_step() {
    local fixture="$1"
    local step="$2"
    shift 2
    local log="$LOG_DIR/${fixture}_${step}.log"
    echo "== [$fixture] $step =="
    set +e
    "$@" 2>&1 | tee "$log"
    local status=${PIPESTATUS[0]}
    set -e
    if [[ $status -ne 0 ]]; then
        extract_invariants "$fixture" "$step" "$log"
    fi
    return $status
}

extract_invariants() {
    local fixture="$1"
    local step="$2"
    local log="$3"
    {
        echo "## fixture=$fixture step=$step"
        echo "- log: $log"
        local found=0
        if rg -n "return_solver:" "$log" >/tmp/.inv_return_solver.$$ 2>/dev/null; then
            found=1
            echo "- return_solver facts:"
            sed 's/^/  - /' /tmp/.inv_return_solver.$$
        fi
        if rg -n "^error\\[E[0-9]+\\]:" "$log" >/tmp/.inv_rust_errors.$$ 2>/dev/null; then
            found=1
            echo "- rustc error facts:"
            sed 's/^/  - /' /tmp/.inv_rust_errors.$$
        fi
        if rg -n "^error:" "$log" >/tmp/.inv_rust_errors_plain.$$ 2>/dev/null; then
            found=1
            echo "- parser/build error facts:"
            sed 's/^/  - /' /tmp/.inv_rust_errors_plain.$$
        fi
        if rg -n "cannot find value|cannot find function|missing structural return completeness|without return-producing op" "$log" >/tmp/.inv_signals.$$ 2>/dev/null; then
            found=1
            echo "- structural signal facts:"
            sed 's/^/  - /' /tmp/.inv_signals.$$
        fi
        if rg -n "attempting to make an HTTP request, but --offline was specified|no matching package named" "$log" >/tmp/.inv_env.$$ 2>/dev/null; then
            found=1
            echo "- environment/dependency facts:"
            sed 's/^/  - /' /tmp/.inv_env.$$
        fi
        if rg -n 'expected identifier, found reserved identifier `_`|cannot parse .*\.rs|comparison operators cannot be chained|expected item, found keyword `let`' "$log" >/tmp/.inv_syntax.$$ 2>/dev/null; then
            found=1
            echo "- syntax-structure facts:"
            sed 's/^/  - /' /tmp/.inv_syntax.$$
        fi
        if rg -n "model_json::_::_serde|core::prompt_config::_::_serde" "$log" >/tmp/.inv_invariant_serde.$$ 2>/dev/null; then
            found=1
            echo "- invariant candidates:"
            echo '  - use-path normalization must never emit reserved `_` path segments.'
            sed 's/^/  - evidence: /' /tmp/.inv_invariant_serde.$$
        fi
        if rg -n '\{alloc[0-9]+:|expected item, found keyword `let`' "$log" >/tmp/.inv_invariant_alloc.$$ 2>/dev/null; then
            found=1
            echo "- invariant candidates:"
            echo "  - MIR internal alloc/debug forms must not be emitted as Rust expressions/items."
            sed 's/^/  - evidence: /' /tmp/.inv_invariant_alloc.$$
        fi
        if rg -n "attempting to make an HTTP request, but --offline was specified|no matching package named" "$log" >/tmp/.inv_invariant_offline.$$ 2>/dev/null; then
            found=1
            echo "- non-structural blockers:"
            echo "  - Offline dependency resolution failure; not a capture/projection structural invariant."
            sed 's/^/  - evidence: /' /tmp/.inv_invariant_offline.$$
        fi
        if [[ $found -eq 0 ]]; then
            echo "- no invariant-signature lines detected; inspect full log."
        fi
        echo
    } >> "$REPORT"
    rm -f \
      /tmp/.inv_return_solver.$$ \
      /tmp/.inv_rust_errors.$$ \
      /tmp/.inv_rust_errors_plain.$$ \
      /tmp/.inv_signals.$$ \
      /tmp/.inv_env.$$ \
      /tmp/.inv_syntax.$$ \
      /tmp/.inv_invariant_serde.$$ \
      /tmp/.inv_invariant_alloc.$$ \
      /tmp/.inv_invariant_offline.$$ || true
}

run_fixture() {
    local fixture="$1"
    local capture_dir="$ROOT/capture/$fixture"
    local capture_json="$capture_dir/canon_capture.json"
    local emit_dir="$ROOT/emit/$fixture"
    local failed=0

    run_step "$fixture" capture "$SCRIPT_DIR/run_capture.sh" "$capture_dir" "$capture_json" || failed=1
    run_step "$fixture" clean rm -rf "$emit_dir" || failed=1
    run_step "$fixture" orchestration cargo run -p orchestration -- "$capture_json" "$emit_dir" || failed=1
    run_step "$fixture" fmt_emit bash -lc "cd '$emit_dir' && cargo fmt" || failed=1
    run_step "$fixture" fmt_capture bash -lc "cd '$capture_dir' && cargo fmt" || failed=1
    run_step "$fixture" build_emit bash -lc "cd '$emit_dir' && CARGO_NET_OFFLINE='${CARGO_NET_OFFLINE:-true}' cargo build" || failed=1
    run_step "$fixture" diff python "$ROOT/diff_src_dirs.py" "$capture_dir/src" "$emit_dir/src" || failed=1

    return $failed
}

declare -a FIXTURES=(repomap test_1 semantic-lint conversation canon)
if [[ $# -gt 0 ]]; then
    FIXTURES=("$1")
fi

overall=0
for fixture in "${FIXTURES[@]}"; do
    if ! run_fixture "$fixture"; then
        overall=1
    fi
done

echo "Invariant report written to: $REPORT"
exit $overall
