[package]
name = "canon-tlog-replay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
canon_types = { path = "../canon-types" }
memmap2.workspace = true
rkyv.workspace = true
canon_tlog_writer = { package = "canon-tlog-writer", path = "../tlog-writer" }
crc32fast = "1"
