[package]
name = "canon-meta"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
name = "canon_meta"

[dependencies]
canon-macros = { path = "../canon-macros" }
canon-runtime-events = { path = "../canon-runtime-events" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
