[package]
name = "canon-runtime-supervisor"
version = "0.1.0"
edition = "2021"
autotests = false
autobins = false

[features]
trace = []

[dependencies]
anyhow.workspace = true
canon_decision = { package = "canon-decision", path = "../canon-decision" }
canon_judgment = { package = "canon-judgment", path = "../canon-judgment" }
canon_exec = { path = "../canon-exec" }
serde_json.workspace = true
# canon_builder = { package = "canon-builder", path = "../canon-builder" }
notify = "6"
signal-hook = "0.3"

[[bin]]
name = "canon-runtime-supervisor"
path = "src/bin/supervisor.rs"
test = false
bench = false
doctest = false
