[package]
name = "rename"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
prettyplease = "0.2"
proc-macro2 = "1"
syn = { version = "2", features = ["full", "visit-mut", "visit"] }
walkdir = "2.5"
regex = "1"
serde_json = "1"
num_cpus = "1"
chrono = "0.4"
canon = { path = "../../canon" }
canon-analyzer = { path = "../../canon-analyzer" }
canon-capture = { path = "../../canon-capture" }
cargo = { path = "/workspace/git_repos/cargo" }
cargo-util = { path = "/workspace/git_repos/cargo/crates/cargo-util" }
