[env]
CFG_RELEASE = "1.80.0"
CFG_RELEASE_CHANNEL = "nightly"
CFG_COMPILER_HOST_TRIPLE = "x86_64-unknown-linux-gnu"
CFG_VERSION = "0.0.0"
CFG_VER_HASH = "unknown"
CFG_VER_DATE = "1970-01-01"
CFG_DEFAULT_CODEGEN_BACKEND = "llvm"
RUSTC_INSTALL_BINDIR = "bin"
