#![feature(rustc_private)]

extern crate rustc_driver;
extern crate rustc_interface;
extern crate rustc_middle;
extern crate rustc_session;
extern crate rustc_hir;
extern crate rustc_span;
extern crate rustc_ast;
extern crate rustc_abi;

#[cfg(not(canon_rustc_typegen))]
pub mod runtime;
pub mod event_stream;
pub mod rustc;
// snapshot module removed: snapshots are generated by reports
pub mod types;
#[cfg(not(canon_rustc_typegen))]
pub mod capture;

#[cfg(not(canon_rustc_typegen))]
pub mod artifacts;
pub mod log;
pub mod invariants;
