[package]
name = "canon-storage-eventlog"
version = "0.1.0"
edition = "2021"
autotests = false
autobins = false

[lib]
path = "src/lib.rs"
name = "canon_event_store"

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
memmap2.workspace = true
rkyv.workspace = true
crc32fast = "1"
canon_event = { package = "canon-runtime-events", path = "../canon-runtime-events" }

[[bin]]
name = "read_tlog"
path = "src/bin/read_tlog.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "verify_tlog_equivalence"
path = "src/bin/verify_tlog_equivalence.rs"
test = false
bench = false
doctest = false
