// @generated by canon_kernel_typegen. Do not edit by hand.
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone)]
pub enum KernelEvent {
    NodeDefined {
        symbol: String,
        kind: String,
    },
    EdgeDefined {
        src: String,
        dst: String,
        kind: String,
    },
    FileSeen {
        path: String,
    },
}

#[derive(Debug, Clone)]
pub struct EventDelta {
    pub tick: u64,
    pub op: KernelEvent,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EventMask(u8);

impl EventMask {
    pub const NONE: EventMask = EventMask(0);
    pub const NODE_DEFINED: EventMask = EventMask(1 << 0);
    pub const EDGE_DEFINED: EventMask = EventMask(1 << 1);
    pub const FILE_SEEN: EventMask = EventMask(1 << 2);
    pub const ALL: EventMask = EventMask(
        Self::NODE_DEFINED.0 | Self::EDGE_DEFINED.0 | Self::FILE_SEEN.0,
    );

    pub fn contains(self, other: EventMask) -> bool {
        (self.0 & other.0) == other.0
    }

    pub fn for_event(event: &KernelEvent) -> EventMask {
        match event {
            KernelEvent::NodeDefined { .. } => Self::NODE_DEFINED,
            KernelEvent::EdgeDefined { .. } => Self::EDGE_DEFINED,
            KernelEvent::FileSeen { .. } => Self::FILE_SEEN,
        }
    }
}

impl std::ops::BitOr for EventMask {
    type Output = EventMask;

    fn bitor(self, rhs: EventMask) -> EventMask {
        EventMask(self.0 | rhs.0)
    }
}

impl std::ops::BitOrAssign for EventMask {
    fn bitor_assign(&mut self, rhs: EventMask) {
        self.0 |= rhs.0;
    }
}

pub trait KernelEventConsumer: Send + Sync {
    fn mask(&self) -> EventMask;
    fn on_event(&mut self, delta: &EventDelta, state: &KernelState);
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KernelState {
    pub tick: u64,
    pub phase: String,
    #[serde(alias = "last_mutation_id")]
    pub last_event_id: u64,
    pub invariant_hash: String,
    pub graph_version: u64,
    #[serde(default)]
    pub known_symbols: HashMap<String, String>,
    #[serde(default)]
    pub known_edges: Vec<(String, String, String)>,
    #[serde(default)]
    pub known_files: HashSet<String>,
}

