// @generated by canon_kernel_typegen. Do not edit by hand.
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum KernelEvent {
    SessionStart {
        project: String,
        #[serde(default)]
        schema: u64,
        #[serde(default)]
        byte_offset: u64,
    },
    NodeDefined {
        symbol: String,
        kind: String,
        #[serde(default)]
        file: String,
        #[serde(default)]
        line: u32,
        #[serde(default)]
        col: u32,
        #[serde(default)]
        lo: u32,
        #[serde(default)]
        hi: u32,
    },
    NodeUpdated {
        symbol: String,
        kind: String,
        #[serde(default)]
        file: String,
        #[serde(default)]
        line: u32,
        #[serde(default)]
        col: u32,
        #[serde(default)]
        lo: u32,
        #[serde(default)]
        hi: u32,
    },
    NodeRemoved {
        symbol: String,
    },
    EdgeDefined {
        src: String,
        dst: String,
        kind: String,
    },
    EdgeRemoved {
        src: String,
        dst: String,
        kind: String,
    },
    FileSeen {
        path: String,
    },
    CallsiteObserved {
        kind: String,
        resolved: bool,
    },
    SymbolDefined {
        symbol: String,
        kind: String,
    },
    SpanDefined {
        symbol: String,
        #[serde(default)]
        file: String,
        #[serde(default)]
        line: u32,
        #[serde(default)]
        col: u32,
        #[serde(default)]
        lo: u32,
        #[serde(default)]
        hi: u32,
    },
    PanicCaptured {
        def_id: String,
        message: String,
        #[serde(default)]
        mir_variant: Option<String>,
        #[serde(default)]
        lowering_stage: Option<String>,
        #[serde(default)]
        file: Option<String>,
        #[serde(default)]
        span: Option<String>,
        #[serde(default)]
        frames: Vec<PanicFrame>,
    },
    WarningCaptured {
        message: String,
    },
    CompilationUnitFinished {
        crate_name: String,
    },
    InvariantViolation {
        message: String,
    },
}

#[derive(Debug, Clone)]
pub struct EventDelta {
    pub id: u64,
    pub tick: u64,
    pub event: KernelEvent,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct KernelState {
    pub tick: u64,
    pub phase: String,
    #[serde(alias = "last_mutation_id")]
    pub last_event_id: u64,
    pub invariant_hash: String,
    pub graph_version: u64,
    #[serde(default)]
    pub known_symbols: HashMap<String, String>,
    #[serde(default)]
    pub known_edges: Vec<(String, String, String)>,
    #[serde(default)]
    pub known_files: HashSet<String>,
    #[serde(default)]
    pub removed_symbols: HashSet<String>,
    #[serde(default)]
    pub removed_edges: Vec<(String, String, String)>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanicFrame {
    pub frame_index: usize,
    pub symbols: Vec<PanicSymbol>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanicSymbol {
    pub symbol: String,
    pub file: Option<String>,
    pub line: Option<u32>,
}
