[package]
name = "canon_query"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "canon_query"
path = "src/lib.rs"

[features]
default = ["cuda"]
cuda = []

[dependencies]
serde_json.workspace = true
canon_types = { path = "../canon-types" }
canon_event_log = { package = "canon-event-log", path = "../event-log" }

[dev-dependencies]
