[package]
name = "canon-planning-agent"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "canon_agent"

[dependencies]
toml.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite.workspace = true
futures-util.workspace = true
once_cell.workspace = true
anyhow.workspace = true
rand.workspace = true
rayon.workspace = true
algorithms = { path = "../../algorithms" }
canon_event = { package = "canon-runtime-events", path = "../canon-runtime-events" }
canon_goal = { package = "canon-planning", path = "../canon-planning" }

[features]
default = []
cuda = ["algorithms/cuda"]
