[package]
name = "canon_event_consumers"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
canon_graph = { package = "canon-graph", path = "../canon-graph" }
canon_query = { path = "../canon-query" }
canon_analysis = { package = "canon-analysis", path = "../canon-analysis" }
canon_editor = { package = "canon-editor", path = "../canon-editor" }
canon_event = { package = "canon-event", path = "../canon-event" }
