[package]
name = "canon-agent"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
toml.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite.workspace = true
futures-util.workspace = true
once_cell.workspace = true
anyhow.workspace = true
rand.workspace = true
rayon.workspace = true
algorithms = { path = "../../algorithms" }
canon_event = { package = "canon-event", path = "../canon-event" }

[features]
default = []
cuda = ["algorithms/cuda"]
