[package]
name = "orchestration"
version = "0.1.0"
edition = "2024"

[dependencies]
canon_telemetry = { path = "../canon_telemetry" }
walkdir = "2"
canon = { path = "../canon" }
canon-analyzer = { path = "../canon-analyzer" }
canon-projection = { path = "../canon-projection" }
canon-mutation = { path = "../canon-mutation" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
